server:
  port: 8087
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  application:
    name: api-driver
  redis:
    host: 192.168.121.134
    port: 6379
    database: 0
