server:
  port: 8085

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  application:
    name: service-map

#????key?value
amap:
  key: 0a02ecd651de9640e9f6ab2c3fd2f5ef
